import PDFDocument from 'pdfkit';

// ── Render helper ────────────────────────────────────────────────
const renderPDF = (buildFn, res, filename) => {
  const doc = new PDFDocument({ margin: 0, size: 'A4', autoFirstPage: true });
  const chunks = [];
  doc.on('data', (c) => chunks.push(c));
  doc.on('end', () => {
    const buffer = Buffer.concat(chunks);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Content-Length', buffer.length);
    res.setHeader('Cache-Control', 'no-cache');
    res.status(200).end(buffer);
  });
  doc.on('error', (err) => {
    console.error('PDF error:', err);
    if (!res.headersSent) res.status(500).json({ error: 'PDF generation failed' });
  });
  buildFn(doc);
  doc.end();
};

// ── Sanitize text for PDFKit (Helvetica = Latin-1 only) ─────────
const clean = (text) => {
  if (!text) return '';
  return String(text)
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201c\u201d]/g, '"')
    .replace(/\u2013/g, '-')
    .replace(/\u2014/g, '-')
    .replace(/[\u25b8\u25b6\u25ba\u2192\u2022\u25cf]/g, '')
    .replace(/[^\x00-\xff]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
};

// ── Resume PDF ───────────────────────────────────────────────────
export const generateResumePDF = (resumeData, res) => {
  renderPDF((doc) => {
    const M = 50;                    // margin
    const PW = 595;                  // A4 width pts
    const CW = PW - M * 2;          // content width
    const primary  = '#1e40af';
    const dark     = '#1e293b';
    const muted    = '#64748b';
    const divider  = '#cbd5e1';

    // ── Section heading ─────────────────────────────────────
    const heading = (title) => {
      if (doc.y > 710) doc.addPage();
      doc.moveDown(0.6);
      doc.fontSize(10.5).font('Helvetica-Bold').fillColor(primary)
        .text(title, M, doc.y, { width: CW });
      const ly = doc.y + 1;
      doc.moveTo(M, ly).lineTo(M + CW, ly)
        .strokeColor(primary).lineWidth(0.7).stroke();
      doc.moveDown(0.55);
    };

    // ── Bullet line ─────────────────────────────────────────
    const bullet = (text) => {
      if (doc.y > 750) doc.addPage();
      const bx = M + 10;
      const tx = M + 20;
      const tw = CW - 20;
      const cy = doc.y;
      doc.fontSize(9.5).font('Helvetica').fillColor(dark)
        .text('\u2022', bx, cy, { width: 10, lineBreak: false });
      doc.fontSize(9.5).font('Helvetica').fillColor(dark)
        .text(clean(text), tx, cy, { width: tw, lineGap: 1.5 });
    };

    // ════════════════════════════════════════════════════════
    // HEADER
    // ════════════════════════════════════════════════════════
    doc.rect(0, 0, PW, 96).fill(primary);

    const name = clean(resumeData.name) || 'Candidate Name';
    doc.fontSize(22).font('Helvetica-Bold').fillColor('#ffffff')
      .text(name, M, 22, { width: CW, align: 'center', lineBreak: false });

    doc.fontSize(8.5).font('Helvetica').fillColor('#bfdbfe')
      .text('ATS-Optimized Resume  -  Generated by SkillGap AI',
        M, 56, { width: CW, align: 'center', lineBreak: false });

    doc.y = 110;

    // ════════════════════════════════════════════════════════
    // PROFESSIONAL SUMMARY
    // ════════════════════════════════════════════════════════
    if (resumeData.summary) {
      heading('PROFESSIONAL SUMMARY');
      doc.fontSize(9.5).font('Helvetica').fillColor(dark)
        .text(clean(resumeData.summary), M, doc.y, { width: CW, lineGap: 2.5 });
      doc.moveDown(0.6);
    }

    // ════════════════════════════════════════════════════════
    // TECHNICAL SKILLS
    // ════════════════════════════════════════════════════════
    if (resumeData.skills?.length > 0) {
      heading('TECHNICAL SKILLS');
      const skillLine = resumeData.skills.map(s => clean(s)).filter(Boolean).join('   |   ');
      doc.fontSize(9.5).font('Helvetica').fillColor(dark)
        .text(skillLine, M, doc.y, { width: CW, lineGap: 2 });
      doc.moveDown(0.6);
    }

    // ════════════════════════════════════════════════════════
    // PROFESSIONAL EXPERIENCE
    // ════════════════════════════════════════════════════════
    if (resumeData.experience?.length > 0) {
      heading('PROFESSIONAL EXPERIENCE');

      resumeData.experience.forEach((exp) => {
        if (doc.y > 700) doc.addPage();

        const role     = clean(exp.role)     || 'Role';
        const company  = clean(exp.company)  || '';
        const duration = clean(exp.duration) || '';

        // Role bold
        doc.fontSize(10.5).font('Helvetica-Bold').fillColor(dark)
          .text(role, M, doc.y, { width: CW });

        // Company | Duration in muted italic
        const meta = [company, duration].filter(Boolean).join('   |   ');
        if (meta) {
          doc.fontSize(9).font('Helvetica-Oblique').fillColor(muted)
            .text(meta, M, doc.y, { width: CW });
        }

        doc.moveDown(0.3);
        (exp.bullets || []).forEach((b) => { bullet(b); doc.moveDown(0.1); });
        doc.moveDown(0.65);
      });
    }

    // ════════════════════════════════════════════════════════
    // PROJECTS
    // ════════════════════════════════════════════════════════
    if (resumeData.projects?.length > 0) {
      heading('PROJECTS');

      resumeData.projects.forEach((proj) => {
        if (doc.y > 700) doc.addPage();

        const pname = clean(proj.name) || 'Project';
        const tech  = clean(proj.tech) || '';

        doc.fontSize(10.5).font('Helvetica-Bold').fillColor(dark)
          .text(pname, M, doc.y, { width: CW });
        if (tech) {
          doc.fontSize(9).font('Helvetica-Oblique').fillColor(muted)
            .text(tech, M, doc.y, { width: CW });
        }

        doc.moveDown(0.3);
        (proj.bullets || []).forEach((b) => { bullet(b); doc.moveDown(0.1); });
        doc.moveDown(0.65);
      });
    }

    // ════════════════════════════════════════════════════════
    // FOOTER
    // ════════════════════════════════════════════════════════
    const fY = doc.page.height - 32;
    doc.moveTo(M, fY - 6).lineTo(M + CW, fY - 6)
      .strokeColor(divider).lineWidth(0.5).stroke();
    doc.fontSize(7.5).font('Helvetica').fillColor(muted)
      .text('Generated by SkillGap AI  -  AI-Powered Resume Optimizer',
        M, fY, { width: CW, align: 'center' });

  }, res, 'ATS_Optimized_Resume.pdf');
};

// ── Interview PDF (unchanged) ────────────────────────────────────
export const generateInterviewPDF = (questions, res) => {
  renderPDF((doc) => {
    const primary = '#065f46';
    const dark = '#1e293b';
    const muted = '#64748b';
    const typeColors = {
      Technical: '#1e40af',
      Behavioral: '#7c3aed',
      'Project-based': '#065f46',
    };

    doc.rect(0, 0, 595, 110).fill(primary);
    doc.fontSize(24).font('Helvetica-Bold').fillColor('#ffffff')
      .text('Interview Preparation Guide', 55, 35, { align: 'center' });
    doc.fontSize(11).font('Helvetica').fillColor('#a7f3d0')
      .text(`${questions.length} Tailored Questions - Generated by SkillGap AI`, { align: 'center' });
    doc.moveDown(3);

    questions.forEach((q, index) => {
      if (doc.y > 720) doc.addPage();
      const color = typeColors[q.type] || primary;
      doc.fontSize(11).font('Helvetica-Bold').fillColor(color)
        .text(`Q${index + 1}.  ${q.question}`, { lineGap: 2 });
      doc.moveDown(0.4);
      doc.fontSize(9).font('Helvetica').fillColor(muted)
        .text(`${q.type || 'General'}  -  Difficulty: ${q.difficulty || 'Medium'}`);
      doc.moveDown(0.4);
      const hintY = doc.y;
      doc.rect(55, hintY, 485, 1).fill('#e2e8f0');
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica-Oblique').fillColor('#374151')
        .text(`Hint: ${q.hint}`, { indent: 8, lineGap: 2 });
      doc.moveDown(1.2);
    });

    const pageHeight = doc.page.height;
    doc.fontSize(8).font('Helvetica').fillColor(muted)
      .text('Generated by SkillGap AI  -  Your AI-Powered Interview Coach',
        55, pageHeight - 40, { align: 'center' });

  }, res, 'Interview_Prep_Guide.pdf');
};

// ── Certificate PDF — Premium Design ────────────────────────────
export const generateCertificatePDF = (certData, res) => {
  const doc = new PDFDocument({ margin: 0, size: 'A4', layout: 'landscape' });
  const chunks = [];
  doc.on('data', (c) => chunks.push(c));
  doc.on('end', () => {
    const buffer = Buffer.concat(chunks);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition',
      `attachment; filename="${certData.name.replace(/\s+/g, '_')}_Certificate.pdf"`);
    res.setHeader('Content-Length', buffer.length);
    res.setHeader('Cache-Control', 'no-cache');
    res.status(200).end(buffer);
  });
  doc.on('error', (err) => {
    console.error('Certificate PDF error:', err);
    if (!res.headersSent) res.status(500).json({ error: 'Failed to generate Certificate PDF' });
  });

  const W = doc.page.width;
  const H = doc.page.height;
  const cx = W / 2;

  const grade = certData.percentage >= 80 ? 'Distinction'
              : certData.percentage >= 60 ? 'Merit'
              : 'Pass';
  const dateStr = new Date().toLocaleDateString('en-US',
    { year: 'numeric', month: 'long', day: 'numeric' });

  // Background
  doc.rect(0, 0, W, H).fill('#0a0f1e');

  // Diagonal stripe texture
  doc.save();
  doc.opacity(0.035);
  for (let x = -H; x < W + H; x += 28) {
    doc.moveTo(x, 0).lineTo(x + H, H).strokeColor('#ffffff').lineWidth(12).stroke();
  }
  doc.restore();

  // Borders
  doc.rect(16, 16, W - 32, H - 32).lineWidth(3.5).strokeColor('#b8960c').stroke();
  doc.rect(24, 24, W - 48, H - 48).lineWidth(1).strokeColor('#1e3a8a').stroke();
  doc.rect(30, 30, W - 60, H - 60).lineWidth(0.5).strokeColor('#1e293b').stroke();

  // Corner dots
  [[38, 38], [W - 38, 38], [38, H - 38], [W - 38, H - 38]].forEach(([x, y]) => {
    doc.circle(x, y, 5).fill('#b8960c');
    doc.circle(x, y, 10).lineWidth(1).strokeColor('#b8960c').stroke();
  });

  // Top accent bar
  doc.rect(42, 42, W - 84, 4).fill('#1e40af');

  // Platform name
  doc.fontSize(9).font('Helvetica').fillColor('#64748b')
    .text('S K I L L G A P   A I', 42, 58, { width: W - 84, align: 'center', characterSpacing: 3 });

  // Main title
  doc.fontSize(27).font('Helvetica-Bold').fillColor('#ffffff')
    .text('CERTIFICATE OF ACHIEVEMENT', 42, 74, { width: W - 84, align: 'center' });

  // Gold underline
  doc.moveTo(cx - 130, 112).lineTo(cx - 10, 112).strokeColor('#b8960c').lineWidth(1).stroke();
  doc.circle(cx, 112, 4).fill('#b8960c');
  doc.moveTo(cx + 10, 112).lineTo(cx + 130, 112).strokeColor('#b8960c').lineWidth(1).stroke();

  // Certify text
  doc.fontSize(11.5).font('Helvetica').fillColor('#94a3b8')
    .text('This is to proudly certify that', 42, 125, { width: W - 84, align: 'center' });

  // Recipient name in gold
  doc.fontSize(33).font('Helvetica-Bold').fillColor('#f0c040')
    .text(certData.name || 'Candidate', 42, 146, { width: W - 84, align: 'center' });

  // Name underline
  doc.moveTo(cx - 210, 192).lineTo(cx + 210, 192).strokeColor('#1e3a8a').lineWidth(1).stroke();

  // Description
  doc.fontSize(11).font('Helvetica').fillColor('#94a3b8')
    .text('has successfully demonstrated proficiency and completed the', 42, 202, { width: W - 84, align: 'center' });

  doc.fontSize(19).font('Helvetica-Bold').fillColor('#60a5fa')
    .text(`${certData.category} Development Certification`, 42, 222, { width: W - 84, align: 'center' });

  doc.fontSize(10).font('Helvetica').fillColor('#475569')
    .text('SkillGap AI  -  AI-Powered Skills Assessment Platform', 42, 250, { width: W - 84, align: 'center' });

  // Score badge
  const bx = cx - 135, by = 272, bw = 270, bh = 50;
  doc.roundedRect(bx, by, bw, bh, 8).fill('#080d1a');
  doc.roundedRect(bx, by, bw, bh, 8).lineWidth(1).strokeColor('#1e3a8a').stroke();

  doc.fontSize(22).font('Helvetica-Bold').fillColor('#34d399')
    .text(`${certData.percentage}%`, bx, by + 7, { width: 90, align: 'center' });
  doc.fontSize(8.5).font('Helvetica').fillColor('#475569')
    .text(`Score: ${certData.score}/${certData.total}`, bx, by + 33, { width: 90, align: 'center' });

  doc.moveTo(bx + 96, by + 10).lineTo(bx + 96, by + 40)
    .strokeColor('#1e3a8a').lineWidth(0.5).stroke();

  doc.fontSize(15).font('Helvetica-Bold').fillColor('#f0c040')
    .text(grade, bx + 100, by + 10, { width: 170, align: 'center' });
  doc.fontSize(8.5).font('Helvetica').fillColor('#475569')
    .text(`${certData.category} Certification`, bx + 100, by + 33, { width: 170, align: 'center' });

  // Bottom accent bar
  doc.rect(42, H - 46, W - 84, 4).fill('#1e40af');

  // Signature row
  const sigY = H - 84;

  // Left — Issuer
  doc.fontSize(11).font('Helvetica-Bold').fillColor('#e2e8f0')
    .text('SkillGap AI', 62, sigY, { width: 200 });
  doc.moveTo(62, sigY + 18).lineTo(242, sigY + 18).strokeColor('#334155').lineWidth(0.75).stroke();
  doc.fontSize(8.5).font('Helvetica').fillColor('#475569')
    .text('Issuing Authority', 62, sigY + 22, { width: 200 });

  // Centre — Seal
  const sealX = cx, sealY = sigY + 12;
  doc.circle(sealX, sealY, 26).fill('#080d1a');
  doc.circle(sealX, sealY, 26).lineWidth(2).strokeColor('#b8960c').stroke();
  doc.circle(sealX, sealY, 20).lineWidth(0.8).strokeColor('#b8960c').stroke();
  doc.fontSize(6.5).font('Helvetica-Bold').fillColor('#b8960c')
    .text('VERIFIED', sealX - 17, sealY - 6, { width: 34, align: 'center' });
  doc.fontSize(5).font('Helvetica').fillColor('#b8960c')
    .text('SKILLGAP AI', sealX - 19, sealY + 4, { width: 38, align: 'center' });

  // Right — Date
  doc.fontSize(11).font('Helvetica-Bold').fillColor('#e2e8f0')
    .text(dateStr, W - 262, sigY, { width: 200, align: 'right' });
  doc.moveTo(W - 242, sigY + 18).lineTo(W - 62, sigY + 18).strokeColor('#334155').lineWidth(0.75).stroke();
  doc.fontSize(8.5).font('Helvetica').fillColor('#475569')
    .text('Date of Issuance', W - 262, sigY + 22, { width: 200, align: 'right' });

  doc.end();
};

