import { useState } from 'react';
import axios from 'axios';
import { BrainCircuit, ChevronRight, CheckCircle2, Download, Share2 } from 'lucide-react';

const API = 'http://localhost:5000/api';

export const TestPage = () => {
  const [step, setStep] = useState('setup'); // setup | loading | quiz | result
  const [name, setName] = useState('');
  const [questions, setQuestions] = useState([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [score, setScore] = useState(0);
  const [error, setError] = useState('');
  const [downloading, setDownloading] = useState(false);

  const startTest = async () => {
    if (!name.trim()) return setError('Please enter your name.');
    setError('');
    setStep('loading');
    
    try {
      const response = await axios.post(`${API}/generate-test`, { name });
      setQuestions(response.data.questions);
      setStep('quiz');
      setCurrentIndex(0);
      setScore(0);
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to generate test. Please try again.');
      setStep('setup');
    }
  };

  const handleAnswer = (selectedOption) => {
    const q = questions[currentIndex];
    if (selectedOption === q.correctAnswer) {
      setScore(s => s + 1);
    }
    
    if (currentIndex + 1 < questions.length) {
      setCurrentIndex(i => i + 1);
    } else {
      setStep('result');
    }
  };

  const downloadCertificate = async () => {
    setDownloading(true);
    try {
      const percentage = Math.round((score / questions.length) * 100);
      const response = await axios.post(`${API}/download/certificate`, {
        name,
        score,
        total: questions.length,
        percentage
      }, {
        responseType: 'blob'
      });
      
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `${name.replace(/\s+/g, '_')}_Certificate.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error(err);
      alert('Failed to download certificate.');
    } finally {
      setDownloading(false);
    }
  };

  const shareText = `I scored ${Math.round((score / questions.length) * 100)}% in the SkillGap AI Frontend Skills Test! 🚀`;

  return (
    <div style={{ maxWidth: 800, margin: '0 auto', minHeight: '60vh' }}>
      
      {/* ── Setup ────────────────────────────────────────────── */}
      {step === 'setup' && (
        <div className="card animate-fade-up" style={{ padding: '48px 32px', textAlign: 'center' }}>
          <div style={{ width: 64, height: 64, background: 'var(--accent-dim)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 24px' }}>
            <BrainCircuit size={28} color="#818cf8" />
          </div>
          <h2 style={{ fontSize: '1.8rem', fontWeight: 800, marginBottom: 12 }}>Take the Frontend Skills Test</h2>
          <p style={{ color: 'var(--text-secondary)', marginBottom: 32, lineHeight: 1.6 }}>
            15 dynamic questions covering HTML, CSS, and JavaScript. Generated by AI so every test is unique. Pass the test to earn your certificate!
          </p>
          
          <div style={{ maxWidth: 400, margin: '0 auto' }}>
            <input
              type="text"
              placeholder="Enter your full name for the certificate"
              value={name}
              onChange={e => { setName(e.target.value); setError(''); }}
              style={{
                width: '100%',
                padding: '14px 20px',
                background: 'rgba(255,255,255,0.03)',
                border: '1px solid var(--border)',
                borderRadius: 12,
                color: 'var(--text-primary)',
                fontSize: '1rem',
                marginBottom: 16,
                outline: 'none',
                boxSizing: 'border-box'
              }}
            />
            {error && <p style={{ color: '#f87171', fontSize: '0.85rem', marginBottom: 16, textAlign: 'left' }}>{error}</p>}
            <button onClick={startTest} className="btn-primary" style={{ width: '100%', justifyContent: 'center' }}>
              Start Test <ChevronRight size={18} />
            </button>
          </div>
        </div>
      )}

      {/* ── Loading ──────────────────────────────────────────── */}
      {step === 'loading' && (
        <div style={{ textAlign: 'center', padding: '64px 0' }}>
          <div className="spinner" style={{ width: 40, height: 40, borderWidth: 3, margin: '0 auto 20px' }} />
          <h3 style={{ fontSize: '1.2rem', fontWeight: 600 }}>Generating your unique test...</h3>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Analyzing topics and crafting questions</p>
        </div>
      )}

      {/* ── Quiz ─────────────────────────────────────────────── */}
      {step === 'quiz' && questions.length > 0 && (
        <div className="card animate-fade-up" style={{ padding: '40px 32px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
            <span style={{ fontSize: '0.85rem', color: 'var(--accent)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              {questions[currentIndex].category}
            </span>
            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
              Question {currentIndex + 1} of {questions.length}
            </span>
          </div>
          
          <div className="progress-track" style={{ marginBottom: 32 }}>
            <div className="progress-fill" style={{ width: `${((currentIndex + 1) / questions.length) * 100}%` }} />
          </div>

          <h3 style={{ fontSize: '1.2rem', fontWeight: 600, lineHeight: 1.6, marginBottom: 32 }}>
            {questions[currentIndex].question}
          </h3>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {questions[currentIndex].options.map((opt, i) => (
              <button
                key={i}
                onClick={() => handleAnswer(opt)}
                style={{
                  background: 'rgba(255,255,255,0.02)',
                  border: '1px solid var(--border)',
                  borderRadius: 12,
                  padding: '16px 20px',
                  color: 'var(--text-primary)',
                  fontSize: '0.95rem',
                  textAlign: 'left',
                  cursor: 'pointer',
                  transition: 'all 0.2s',
                  display: 'flex',
                  alignItems: 'center',
                  gap: 12
                }}
                onMouseEnter={e => { e.currentTarget.style.background = 'var(--bg-card-hover)'; e.currentTarget.style.borderColor = 'var(--border-bright)'; }}
                onMouseLeave={e => { e.currentTarget.style.background = 'rgba(255,255,255,0.02)'; e.currentTarget.style.borderColor = 'var(--border)'; }}
              >
                <span style={{ 
                  width: 24, height: 24, 
                  borderRadius: '50%', 
                  background: 'var(--accent-dim)', 
                  color: '#818cf8', 
                  display: 'flex', alignItems: 'center', justifyContent: 'center', 
                  fontSize: '0.8rem', fontWeight: 700, flexShrink: 0 
                }}>
                  {String.fromCharCode(65 + i)}
                </span>
                {opt}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* ── Result ───────────────────────────────────────────── */}
      {step === 'result' && (
        <div className="card animate-fade-up" style={{ padding: '48px 32px', textAlign: 'center' }}>
          <div style={{ width: 80, height: 80, background: 'var(--green-dim)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 24px' }}>
            <CheckCircle2 size={40} color="var(--green)" />
          </div>
          <h2 style={{ fontSize: '2rem', fontWeight: 800, margin: '0 0 8px' }}>Test Completed!</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '1.1rem', margin: '0 0 32px' }}>
            Great job, <strong style={{ color: 'var(--text-primary)' }}>{name}</strong>. Here is your result:
          </p>

          <div style={{ display: 'inline-flex', flexDirection: 'column', alignItems: 'center', background: 'rgba(255,255,255,0.02)', border: '1px solid var(--border)', borderRadius: 16, padding: '32px 64px', marginBottom: 32 }}>
            <span style={{ fontSize: '3.5rem', fontWeight: 900, color: 'var(--accent)', lineHeight: 1 }}>
              {Math.round((score / questions.length) * 100)}%
            </span>
            <span style={{ fontSize: '1rem', color: 'var(--text-muted)', marginTop: 8 }}>
              Score: {score} / {questions.length}
            </span>
          </div>

          <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
            <button onClick={downloadCertificate} disabled={downloading} className="btn-primary">
              {downloading ? <div className="spinner" style={{ width: 16, height: 16 }} /> : <Download size={16} />}
              Download Certificate
            </button>
            
            <a 
              href={`https://wa.me/?text=${encodeURIComponent(shareText + ' https://skillgap.ai')}`}
              target="_blank" rel="noopener noreferrer"
              className="btn-ghost"
              style={{ textDecoration: 'none', background: '#25D36615', color: '#25D366', borderColor: '#25D36640' }}
            >
              <Share2 size={16} /> WhatsApp
            </a>
            
            <a 
              href={`https://www.linkedin.com/sharing/share-offsite/?url=https://skillgap.ai&summary=${encodeURIComponent(shareText)}`}
              target="_blank" rel="noopener noreferrer"
              className="btn-ghost"
              style={{ textDecoration: 'none', background: '#0a66c215', color: '#0a66c2', borderColor: '#0a66c240' }}
            >
              <Share2 size={16} /> LinkedIn
            </a>
          </div>
        </div>
      )}

    </div>
  );
};
